# Generated by Django 4.1.6 on 2024-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
