# Generated by Django 4.1.6 on 2024-03-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountprofile", "0002_alter_package_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="referral",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
