# Generated by Django 4.1.6 on 2024-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_rename_user_cryptodeposit_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptodeposit',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='currency',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
