# Generated by Django 4.1.6 on 2024-03-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='term',
            new_name='duration',
        ),
    ]
