# Generated by Django 4.1.6 on 2024-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_delete_activity_rename_term_loanapplication_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
