# Generated by Django 4.1.6 on 2024-03-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_withdrawal_user_withdrawal_wallet_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
